[package]
name = "jeff-mitchell-dev-server"
version = "1.5.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
shuttle-axum = "0.24.0"
shuttle-runtime = "0.24.0"
shuttle-static-folder = "0.24.0"
tokio = "1.29.1"
tower-http = { version = "0.4.3", features = ["fs"] }
tracing = "0.1.37"
