[package]
name = "jeff-mitchell-dev-server"
version = "1.35.12"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
shuttle-rocket = "0.35.0"
shuttle-runtime = "0.35.0"

