# Secrets.toml

# Token for Turso database
DB_TURSO_TOKEN="eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTAxNDQ0MzQsImlkIjoiODJhMzIwMDgtMjk5Ny0xMWVlLTk1ODEtMWE4NjY5MWUyODU2In0.wyt0RwxLZdzbHlHNtM5NIQYdo6dkeWB1hKn55Hnr0h8OqAUypWYDpsCt_k8BEJbjZCpVBXfxcbKNiIMhn5hSBQ"